//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/Interactions/Player Controllers.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControllers : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControllers()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player Controllers"",
    ""maps"": [
        {
            ""name"": ""Whole Environment "",
            ""id"": ""fa582375-f243-40cd-8ada-51ad698f6251"",
            ""actions"": [
                {
                    ""name"": ""Play Sound"",
                    ""type"": ""Button"",
                    ""id"": ""061462b4-1040-46a6-940e-6cf9027823e6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3fbb7a7b-467d-4a95-b66b-b67b3301f558"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play Sound"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Whole Environment 
        m_WholeEnvironment = asset.FindActionMap("Whole Environment ", throwIfNotFound: true);
        m_WholeEnvironment_PlaySound = m_WholeEnvironment.FindAction("Play Sound", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Whole Environment 
    private readonly InputActionMap m_WholeEnvironment;
    private IWholeEnvironmentActions m_WholeEnvironmentActionsCallbackInterface;
    private readonly InputAction m_WholeEnvironment_PlaySound;
    public struct WholeEnvironmentActions
    {
        private @PlayerControllers m_Wrapper;
        public WholeEnvironmentActions(@PlayerControllers wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlaySound => m_Wrapper.m_WholeEnvironment_PlaySound;
        public InputActionMap Get() { return m_Wrapper.m_WholeEnvironment; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WholeEnvironmentActions set) { return set.Get(); }
        public void SetCallbacks(IWholeEnvironmentActions instance)
        {
            if (m_Wrapper.m_WholeEnvironmentActionsCallbackInterface != null)
            {
                @PlaySound.started -= m_Wrapper.m_WholeEnvironmentActionsCallbackInterface.OnPlaySound;
                @PlaySound.performed -= m_Wrapper.m_WholeEnvironmentActionsCallbackInterface.OnPlaySound;
                @PlaySound.canceled -= m_Wrapper.m_WholeEnvironmentActionsCallbackInterface.OnPlaySound;
            }
            m_Wrapper.m_WholeEnvironmentActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PlaySound.started += instance.OnPlaySound;
                @PlaySound.performed += instance.OnPlaySound;
                @PlaySound.canceled += instance.OnPlaySound;
            }
        }
    }
    public WholeEnvironmentActions @WholeEnvironment => new WholeEnvironmentActions(this);
    public interface IWholeEnvironmentActions
    {
        void OnPlaySound(InputAction.CallbackContext context);
    }
}
